# prometheus.yml
global:
  scrape_interval: 15s # Scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'krishiconnect-model'
    static_configs:
      - targets: ['host.docker.internal:5000'] # For Windows/Mac
      # For Linux use: ['172.17.0.1:5000'] or your host IP